role="tab"
x-bind:href="tab.href"
x-bind:id="`tab-${tab.id}`"
x-bind:aria-setsize="tabs.length"
x-bind:aria-posinset="index + 1"
x-bind:aria-controls="`tab-panel-${tab.id}`"
x-bind:aria-disabled="tab.disabled"
x-bind:disabled="tab.disabled"
x-bind:aria-selected="(tab.id === activeTab).toString()"
x-on:click.prevent.stop="selectTab(tab.id)"
